### ISSUE TITLE
The mongo data has been tampered after snap update.

### ISSUE THREAD

**Issue by abel533** [wekan/wekan-snap#83] opened 2019-03-01 02:10 UTC
You may find that the card has disappeared.

Query the mongo database to find the following problem:

```json
    "listId" : "PozTHYqCX9P5TcchW",
    "boardId" : "rjkgvdzfSwo5MC7qW",
    "sort" : 0.0625,
    "swimlaneId" : "rjkgvdzfSwo5MC7qW",
    "type" : "cardType-card",
    "archived" : false,
```

the `swimlaneId` should be `6zoz9hutLm9T4h7Rz`，but now it's the same as boardId, then the card has disappeared.

Snap can't disable updates, how to avoid this serious bug caused by automatic updates.

**Comment by xet7** [comment] 2019-03-01 02:38
@abel533 

What is your Wekan versions? You see it with `sudo snap list`

Docker version of Wekan does not update automatically, it's used by version tag like this at docker-compose.yml:
```
image: quay.io/wekan/wekan:v2.33
```
With Wekan, you need to have backups of database at least daily, preferably more often. Wekan still has bugs that can make Wekan board not load anymore, like moving some card away from subtasks, or linking to card itself causing recursive loop, so you need to be able to restore, even when not having automatic updates.

@andresmanelli Can you look at this?

Related https://github.com/wekan/wekan/issues/2209

**Comment by xet7** [comment] 2019-03-01 02:55
Hmm, that's stange bug. I'll also look at source code changes how has this happened.

**Comment by xet7** [comment] 2019-03-01 03:02
@abel533

I can't figure out anything that would cause that in changes between previous and newest Wekan release that would have caused that. It would really help if you could tell what Wekan version you have.

**Comment by abel533** [comment] 2019-03-01 04:10
Version:
```
Name   Version    Rev   Tracking  Publisher   Notes
core   16-2.37.2  6405  stable    canonical✓  core
wekan  2.33       449   stable    xet7        -
```

When you add or modify a card now, there will still be a problem with the swimlaneId becoming a boardId.

![image](https://user-images.githubusercontent.com/1787798/53615867-fb090780-3c1a-11e9-98e4-c48f1ad34b05.png)

**Comment by abel533** [comment] 2019-03-01 04:12
How to use the snap to downgrade the wekan version?

**Comment by xet7** [comment] 2019-03-01 04:54
@abel533 

https://snapcraft.io has snap docs.

**Comment by xet7** [comment] 2019-03-01 05:01
Just guessing, maybe it's this https://github.com/wekan/wekan/issues/2213

I will revert it and add new Wekan release.

**Comment by abel533** [comment] 2019-03-01 05:25
I also found filtering problems yesterday.

**Comment by xet7** [comment] 2019-03-01 05:29
Wekan Snap version is currently building, it will be released soon.

**Comment by xet7** [comment] 2019-03-01 05:35
Well, "soon" depends how fast Snap Store validates new upload of Wekan release. Sometimes it's fast, but sometimes it takes one hour.

**Comment by xet7** [comment] 2019-03-01 05:38
@abel533 

Thanks a lot for reporting this issue! Hmm, I did not sleep tonight, it's morning already...

**Comment by abel533** [comment] 2019-03-01 05:44
I will always pay attention to the update of the snap version, and feedback after the update.

**Comment by xet7** [comment] 2019-03-01 05:49
Thanks! Wekan has a huge amount of advanced features so I do depend on bug reports etc community feedback to know what does not work.

**Comment by xet7** [comment] 2019-03-01 05:53
Now Wekan snap is released! Please test. This updates immediately:
```
sudo snap refresh
```

**Comment by xet7** [comment] 2019-03-01 06:02
Only other change that I did not revert yet were performance improvements https://github.com/wekan/wekan/pull/2214 that add indexes to MongoDB and do group queries to database, but I would think that does not actually change queries in any way.

**Comment by abel533** [comment] 2019-03-01 06:11
I have updated.

**Comment by abel533** [comment] 2019-03-01 06:12
Filtering problems still exist

**Comment by xet7** [comment] 2019-03-01 06:13
Sure, filter "fix" was reverted. But did mongodb tampering get fixed?

**Comment by abel533** [comment] 2019-03-01 06:29
SwimlaneId problem still exists, I'll try a lower version.

**Comment by abel533** [comment] 2019-03-01 06:37
```
redis@redis:~$ sudo snap revert --revision=446 wekan
wekan reverted to 2.31
redis@redis:~$ ll /snap/wekan/
total 8
drwxr-xr-x  5 root root 4096 Mar  1 14:34 ./
drwxr-xr-x  5 root root 4096 Jan 10 09:47 ../
drwxr-xr-x 13 root root  671 Feb 28 18:57 446/
drwxr-xr-x 13 root root  671 Mar  1 05:47 449/
drwxr-xr-x 13 root root  671 Mar  1 13:25 451/
lrwxrwxrwx  1 root root    3 Mar  1 14:34 current -> 446/
```

**Comment by abel533** [comment] 2019-03-01 07:49
```
redis@redis:~$ snap list --all wekan
Name   Version  Rev  Tracking  Publisher  Notes
wekan  2.31     446  stable    xet7       -
wekan  2.33     449  stable    xet7       disabled
wekan  2.34     451  stable    xet7       disabled
```

446 also has problems. I can't switch to a lower version.

**Comment by bentiss** [comment] 2019-03-01 10:12
> 446 also has problems. I can't switch to a lower version.

I can help bisecting the problem. However, I can't seem to reproduce the issue. Do you have a reliable reproducer? Neither adding nor modifying a card makes it disappear in v2.33, so I must not be doing the right thing to expose the bug.

**Comment by xet7** [comment] 2019-03-01 12:23
@abel533 

You could have something wrong in your database like [circular reference bug](https://github.com/wekan/wekan/issues/2202) or something else. It can not be fixed with downgrade because downgrade does not change database contents. You coud try exporting all boards to Wekan JSON and importing to new empty Wekan database. You can empty database this way in snap:
```
sudo snap stop wekan.wekan
mongo --port 27019
use wekan
db.dropDatabase();
exit
sudo snap start wekan.wekan
```

**Comment by xet7** [comment] 2019-03-01 12:24
And, make backup first before trying above.

**Comment by xet7** [comment] 2019-03-01 12:28
Also, this does not restore all users, so you would need to copy list from webbrowser and create them again, or edit database.

**Comment by xet7** [comment] 2019-03-01 12:30
Another one to try is, does this bug happen only on one board? If you create new board, is the bug there too?

**Comment by xet7** [comment] 2019-03-01 12:32
I would guess that if you find the difference by comparing working and not-working Wekan boards, and fix some small change to your existing database, you could fix this.

**Comment by xet7** [comment] 2019-03-01 12:33
Also on my Wekan boards I have not noticed this bug at all. I will add filter fix back in next Wekan release.

**Comment by abel533** [comment] 2019-03-02 03:22
This problem exists in many billboards.

When this problem occurs again, I will check all the data to find the problem.

**Comment by abel533** [comment] 2019-03-02 06:12
Test in a new board. 

Create a new card and drag it in the current list.

The following are the new and updated messages:
```json
[
  [
    {
      "msg": "method",
      "method": "/cards/insert",
      "params": [
        {
          "title": "111",
          "members": [],
          "labelIds": [],
          "customFields": [],
          "listId": "FmAiv5rD3spesKK5f",
          "boardId": "7qBtoFy5iD9jEPj2T",
          "sort": 3,
          "swimlaneId": "xtTDXEpP9q4tjJxAb",
          "type": "cardType-card",
          "archived": false,
          "parentId": "",
          "coverId": "",
          "createdAt": { "$date": 1551506948812 },
          "dateLastActivity": { "$date": 1551506948812 },
          "description": "",
          "requestedBy": "",
          "assignedBy": "",
          "spentTime": 0,
          "isOvertime": false,
          "userId": "oup6ydF2SXPsZXa3X",
          "subtaskSort": -1,
          "linkedId": ""
        }
      ],
      "id": "30",
      "randomSeed": "e3df1685305781720f82"
    }
  ],
  [
    {
      "msg": "method",
      "method": "/cards/update",
      "params": [
        { "_id": "Q9bhk3pSQLteKSALW" },
        {
          "$set": {
            "swimlaneId": "7qBtoFy5iD9jEPj2T",
            "listId": "FmAiv5rD3spesKK5f",
            "boardId": "7qBtoFy5iD9jEPj2T",
            "sort": 3,
            "dateLastActivity": { "$date": 1551506950810 }
          }
        },
        {}
      ],
      "id": "31"
    }
  ]
]

```

Tests show that only specific users will update the wrong swimlaneId.  My own account does not have this problem. Can you see the reason?

**Comment by abel533** [comment] 2019-03-02 06:28
This was tested in a new board.
```json
{
  "_format": "wekan-board-1.0.0",
  "_id": "QEvKyvvi69yaentZo",
  "title": "mytest",
  "permission": "private",
  "slug": "mytest",
  "archived": false,
  "createdAt": "2019-03-02T06:01:03.522Z",
  "labels": [
    { "color": "green", "_id": "TEP9nP", "name": "" },
    { "color": "yellow", "_id": "Kuwkao", "name": "" },
    { "color": "orange", "_id": "fMPjPp", "name": "" },
    { "color": "red", "_id": "wPvvQ8", "name": "" },
    { "color": "purple", "_id": "vKETFv", "name": "" },
    { "color": "blue", "_id": "wyoTSy", "name": "" }
  ],
  "members": [
    {
      "userId": "oup6ydF2SXPsZXa3X",
      "isAdmin": true,
      "isActive": true,
      "isNoComments": false,
      "isCommentOnly": false
    }
  ],
  "color": "belize",
  "subtasksDefaultBoardId": null,
  "subtasksDefaultListId": null,
  "allowsSubtasks": true,
  "presentParentTask": "no-parent",
  "isOvertime": false,
  "type": "board",
  "cards": [
    {
      "_id": "AiABTyGhSjnHBL9n5",
      "title": "test",
      "members": [],
      "labelIds": [],
      "customFields": [],
      "listId": "gSQcK4AyA3K3A9hpc",
      "sort": 0,
      "swimlaneId": "QEvKyvvi69yaentZo",
      "type": "cardType-card",
      "archived": false,
      "parentId": "",
      "coverId": "",
      "createdAt": "2019-03-02T06:01:36.205Z",
      "dateLastActivity": "2019-03-02T06:01:51.601Z",
      "description": "",
      "requestedBy": "",
      "assignedBy": "",
      "spentTime": 0,
      "isOvertime": false,
      "userId": "oup6ydF2SXPsZXa3X",
      "subtaskSort": -1,
      "linkedId": ""
    }
  ],
  "lists": [
    {
      "_id": "gSQcK4AyA3K3A9hpc",
      "title": "test1",
      "sort": 1,
      "type": "list",
      "archived": false,
      "swimlaneId": "",
      "createdAt": "2019-03-02T06:01:07.339Z",
      "wipLimit": { "value": 1, "enabled": false, "soft": false }
    }
  ],
  "swimlanes": [
    {
      "_id": "4NSgRBp5sW4DRKCYQ",
      "title": "Default",
      "archived": false,
      "createdAt": "2019-03-02T06:01:03.549Z",
      "type": "swimlane",
      "sort": 0,
      "updatedAt": "2019-03-02T06:01:03.660Z"
    }
  ],
  "activities": [
    {
      "_id": "Q8vZjxt8pEpYgoxjT",
      "userId": "oup6ydF2SXPsZXa3X",
      "activityType": "createCard",
      "listName": "test1",
      "listId": "gSQcK4AyA3K3A9hpc",
      "cardId": "AiABTyGhSjnHBL9n5",
      "cardTitle": "test",
      "swimlaneName": "Default",
      "swimlaneId": "4NSgRBp5sW4DRKCYQ",
      "createdAt": "2019-03-02T06:01:36.220Z"
    },
    {
      "_id": "bEJfo4ugAHxSGszNr",
      "userId": "oup6ydF2SXPsZXa3X",
      "type": "list",
      "activityType": "createList",
      "listId": "gSQcK4AyA3K3A9hpc",
      "createdAt": "2019-03-02T06:01:07.342Z"
    },
    {
      "_id": "x72geBRfuqxuZ6xM7",
      "userId": "oup6ydF2SXPsZXa3X",
      "type": "swimlane",
      "activityType": "createSwimlane",
      "swimlaneId": "4NSgRBp5sW4DRKCYQ",
      "createdAt": "2019-03-02T06:01:03.552Z"
    },
    {
      "_id": "aRn7QdRBdqvN9r4WA",
      "userId": "oup6ydF2SXPsZXa3X",
      "type": "board",
      "activityTypeId": "QEvKyvvi69yaentZo",
      "activityType": "createBoard",
      "createdAt": "2019-03-02T06:01:03.527Z"
    }
  ],
  "customFields": [],
  "comments": [],
  "rules": [],
  "checklists": [],
  "checklistItems": [],
  "subtaskItems": [],
  "triggers": [],
  "actions": [],
  "attachments": [],
  "users": [
    {
      "_id": "oup6ydF2SXPsZXa3X",
      "username": "maishuyu",
      "profile": {
        "fullname": "msy",
        "initials": "msy"
      }
    }
  ]
}
```

**Comment by abel533** [comment] 2019-03-02 08:08
docker compose, use `wekanteam/wekan:v2.17`.

The same user performs the same operation.
 
 There is no problem with this version. Judging from the data, swimlaneId has been updated in the new version.

```json
{
    "msg": "method",
    "method": "/cards/update",
    "params": [
        {
            "_id": "JeFGz88Ykt9aeXe5m"
        },
        {
            "$set": {
                "listId": "gSQcK4AyA3K3A9hpc",
                "boardId": "QEvKyvvi69yaentZo",
                "sort": 4,
                "dateLastActivity": {
                    "$date": 1551513769979
                }
            }
        },
        {}
    ],
    "id": "5"
}
```

**Comment by abel533** [comment] 2019-03-02 09:53
I changed from snap to dock-compose.

**Closed as completed** 2019-03-05 23:17 UTC
Labels: bug
